spring.application.name=TradeShift-backend
server.port=5455
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/tradeshift
spring.datasource.username=root
spring.datasource.password=Pravin@27042005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

finnhub.api.key=d3acvehr01qlsbrqt0a0d3acvehr01qlsbrqt0ag

# 1. JWT Secret Key (MUST be long, random, and Base64-encoded)
# Example: Use a strong generator. This one is 32 random characters Base64-encoded.
application.security.jwt.secret-key=RmRzVk9rQjdHNE9xQ3pIMnN3eGxXNUp4VjlyZGd3Z29PZjI3Y1J2NlZ3Rk9hZ3BwVlI1dQ==

# 2. JWT Expiration Time (Time in milliseconds for token validity)
# Example: 86400000 milliseconds = 24 hours
application.security.jwt.expiration=86400000

